# Generated by Django 2.0.3 on 2018-03-19 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PEapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved')], default='PE', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'permissions': (('view_task', 'View task'),)},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'permissions': (('view_task', 'View task'),)},
        ),
        migrations.AddField(
            model_name='approval',
            name='prescription_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PEapp.Prescription'),
        ),
        migrations.AddField(
            model_name='approval',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
